#include <stdint.h>

#define BQ_SAMPLING_PERIOD_MS 1000
#define CAN_HEARTBEAT_PERIOD_MS 3000

#define NUM_BQ_DEVICES 1
#define CELLS_PER_DEVICE 10
#define THERMISTORS_PER_DEVICE 7

#define TOTAL_CELLS (NUM_BQ_DEVICES * CELLS_PER_DEVICE)
#define TOTAL_THERMISTORS (NUM_BQ_DEVICES * THERMISTORS_PER_DEVICE)

#define MAX_BROAD_READ_DATA_SIZE 11
#define BQ_V_LSB_ADC 190.73 * 0.000001
#define OV_THRESH 2.7
#define UV_THRESH 1.2
#define OW_THRESH 0.8

uint8_t ReverseByteBits(uint8_t b);
